#       _               _               
# _ __ (_)_ __ ___   __| | _____      __
#| '_ \| | '_ ` _ \ / _` |/ _ \ \ /\ / /
#| | | | | | | | | | (_| | (_) \ V  V / 
#|_| |_|_|_| |_| |_|\__,_|\___/ \_/\_/  


# Start external programs

[[startProcess]]
command = "pkill nimdow"
keys = [ "Delete" ]
modifiers = [ "control", "alt" ]

[[startProcess]]
command = "brave"
keys = [ "w" ]
modifiers = [ "super" ]

[[startProcess]]
command = "rofi -show drun"
keys = [ "p" ]
modifiers = [ "super" ]

[[startProcess]]
command = "kitty -e fish"
keys = [ "Return" ]
modifiers = [ "super" ]

[[startProcess]]
command = "keepassxc"
keys = [ "k" ]
modifiers = [ "super", "shift", "control" ]

# Example: Start process when region is clicked, see github wiki for what constitutes a region
# [[startProcess]]
# command = "notify-send \"Id: %1, rx: %2, cx: %4, w: %6\""
# clickRegion = 0

[autostart]
exec = [
  "xsetroot -cursor_name left_ptr",
  "picom",
  "nitrogen --restore",
  "librewolf",
#  "discord",
  "armcord",
#  "sxhkd",
  "syncthing --no-browser",
#  "~/dotfiles/scripts/statusbar",
]

[settings]
  # Window settings
  borderWidth = 1
  borderColorUnfocused = "#282828"
  borderColorFocused = "#689d6a"
  borderColorUrgent = "#cc241d"
  # Bar settings
  barHeight = 20
  windowTitlePosition = "left"
  barBackgroundColor = "#282828"
  barForegroundColor = "#ebdbb2"
  barSelectionColor = "#b16286"
  barUrgentColor = "#cc241d"
  barFonts = [
    "monospace:size=10:antialias=true",
    "NotoColorEmoji:size=10:antialias=true"
  ]
  # Layout settings
  gapSize = 0
  outerGap = 0
  resizeStep = 10
  # Scratchpad settings
  scratchpadWidth = 500
  scratchpadHeight = 300
  # General settings
  loggingEnabled = false
  reverseTagScrolling = false

# Window manager controls
[controls]
  [controls.reloadConfig]
  keys = [ "r" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPrevious]
  keys = [ "k" ]
  modifiers = [ "super" ]

  [controls.focusNext]
  keys = [ "j" ]
  modifiers = [ "super" ]

  [controls.moveWindowPrevious]
  keys = [ "k" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowNext]
  keys = [ "j" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleFullscreen]
  keys = [ "f" ]
  modifiers = [ "super" ]

  [controls.destroySelectedWindow]
  keys = [ "q" ]
  modifiers = [ "super" ]

#  [controls.goToPreviousTag]
#  keys = [ "w" ]
#  modifiers = [ "super" ]

  [controls.moveWindowToPreviousTag]
  keys = [ "w" ]
  modifiers = [ "super", "shift" ]

  [controls.focusPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super" ]

  [controls.focusNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super" ]

  [controls.moveWindowToPreviousMonitor]
  keys = [ "comma" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToNextMonitor]
  keys = [ "period" ]
  modifiers = [ "super", "shift" ]

  [controls.increaseMasterCount]
  keys = [ "z" ]
  modifiers = [ "super" ]

  [controls.decreaseMasterCount]
  keys = [ "x" ]
  modifiers = [ "super" ]

  [controls.toggleFloating]
  keys = [ "space" ]
  modifiers = [ "super" ]

  [controls.jumpToUrgentWindow]
  keys = [ "u" ]
  modifiers = [ "super" ]

  [controls.goToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super" ]

  [controls.goToLeftTag]
  keys = [ "Left" ]
  modifiers = [ "super" ]

  [controls.goToRightTag]
  keys = [ "Right" ]
  modifiers = [ "super" ]

  [controls.moveWindowToTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToLeftTag]
  keys = [ "Left" ]
  modifiers = [ "super", "shift" ]

  [controls.moveWindowToRightTag]
  keys = [ "Right" ]
  modifiers = [ "super", "shift" ]

  [controls.toggleTagView]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "control" ]

  [controls.toggleWindowTag]
  keys = [ "1", "2", "3", "4", "5", "6", "7", "8", "9" ]
  modifiers = [ "super", "shift", "control" ]

	[controls.increaseMasterWidth]
	keys = [ "l" ]
	modifiers = [ "super" ]

	[controls.decreaseMasterWidth]
	keys = [ "h" ]
	modifiers = [ "super" ]

  [controls.moveWindowToScratchpad]
  keys = [ "s" ]
  modifiers = [ "super", "shift" ]

  [controls.popScratchpad]
  keys = [ "s" ]
  modifiers = [ "super" ]

  [controls.rotateClients]
  keys = [ "r" ]
  modifiers = [ "super" ]

  [controls.toggleStatusBar]
  keys = [ "b" ]
  modifiers = [ "super" ]

# Example monitor settings:
# [monitors]
  # [monitors.default.tags]
  # 1.displayString = "one"
  # 2.displayString = "foobar"
  # Set the number of master windows for ALL monitors.
  # all.numMasterWindows = 2
  # all.defaultMasterWidthPercentage = 60

  # [monitors.1.tags]
  # 2.displayString = "two"
  # Set the number of master windows per-monitor.
  # all.numMasterWindows = 3
  # Set the number of master windows per-tag.
  # 2.numMasterWindows = 1

  # [monitors.2.tags]
  # 2.displayString = "too"



# App Rules
# Example:
# [[appRule]]
# class = "st"
# instance = "st"
# title = "st"
# monitor = 1
# tags = [ 1, 4, 7 ]
# state = "floating" # normal, floating, and fullscreen are all valid.

#[[appRule]]
#class = "Brave-browser"
#instance = ""
#title = ""
#monitor = 1
#tags = [ 2 ]
#state = "normal"


[[appRule]]
class = "armcord"
instance = ""
title = ""
monitor = 2
tags = [ 1 ]
state = "normal"


[[appRule]]
class = "Video-downloader"
instance = ""
title = ""
state = "floating"
