#!/bin/sh
random=$(seq 3 | shuf -n 1)


case $random in

	1)
	./dotfiles/scripts/bunnyfetch
	;;


	2)
	fm6000 -dog -color "blue" --shell=fish -nd
	;;


	3)
	aura -n  'user shell' -c 'c4 c6'
	;;


esac
